[project]
name = "aiwolf-nlp-agent-llm"
version = "0.2.3"
description = "aiwolf-nlp-agent-llm"
license = { file = "LICENSE" }
requires-python = ">=3.11"
readme = "README.md"
dependencies = ["aiwolf-nlp-common==0.5.2", "google-genai>=1.5.0"]

authors = [
    { name = "aiwolfdial", email = "aiwolf@kanolab.net" },
    { name = "nwatanabe", email = "nwatanabe@kanolab.net" },
    { name = "ysahashi", email = "ysahashi@kanolab.net" },
]
maintainers = [
    { name = "aiwolfdial", email = "aiwolf@kanolab.net" },
    { name = "nwatanabe", email = "nwatanabe@kanolab.net" },
    { name = "ysahashi", email = "ysahashi@kanolab.net" },
]
keywords = ["aiwolf"]

[project.urls]
Homepage = "https://aiwolfdial.github.io/aiwolf-nlp/"
